# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

use_frameworks!


target 'LatestNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  
    pod 'SDWebImage'
    pod "TinyConstraints"
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxDataSources', '~> 4.0'

  # Pods for LatestNews

end

target 'LatestNewsUnitTests' do
    pod 'RxSwift', '~> 5'
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'

end
